### ISSUE TITLE
About page revamp

### ISSUE THREAD

**Issue by beingeek** [phamos-eu/phamos#15]
## The goal 
Refactor  phamos.eu/about page and changing data source, moving Customization from 'About Us Settings' to 'Phamos Settings' (new doctype).

## Context
- At the moment phamos.eu/about page is overridden via Web Page and it's reading profile data from newly created table 'Team Profile Links' instead of 'Team Members' table in  'About Us Settings'.
- Now we are planning to not use 'About Us Settings' and discard it usage in phamos.eu/about , this will be achieved by creating new Doctype, and making required changes in Web Page to render it from new Doctype

## TODOs
- [x] Make a new Doctype 'phamos Settings', ~~much like~~ with necessary data from 'About Us Settings'
- [x] Make a design of Doctype 'phamos Settings', based on idea of HTML page which we want to render. 
- [x] Remove Customization from  'About Us Settings' and leave it in vanilla state.
- [x] Make changes in Web Page HTML field to render from new source.
