### ISSUE TITLE
External Project Participants: billing Timesheets

### ISSUE THREAD

**Issue by roquegv** [phamos-eu/phamos#2]
## The goal
The goal is to be able to bill timesheets mostly using ERPNext standard documents and functionalities.  

## Context
- Suppliers (e.g. developers) usually send invoices as PDFs. This includes data such as: invoice number, supplier name, amounts.
there is a new new doctype called Accounting Receipt which holds data from the invoices sent by the supplier
- This Accounting Receipt works similar than a purchase receipt. The main idea is to have a preliminary document to check that all data are correct before creating a purchase invoice. It should include data: supplier, table of timesheets, project, amounts.
- Accounting Receipt corresponds to one and only one Purchase Invoice (ont-to-one relationship)
- The general workflow could be:
    - Create timesheets records documents (and subsequent timesheet documents) as usual
    - Select the Timesheet documents you want to process (this could be achieved selecting the documents manually or via a popup that ask for the project and a date range)
    - Create an Accounting Receipt document with all the selected Timesheets
    - Have a button in Accounting Receipt form to create a Purchase Invoice with the item of "Service by <Supplier>" with the quantity (hours) and a hourly rate (from the item price). 

## TODOs
- [ ] Propose a design for the Accounting Receipt doctype 
- [ ] Create Accounting Receipt doctype
- [ ] Implement a process to create Accounting Receipt documents from Timesheets
- [ ] Implement a process to create Purchase Invoices documents from Accounting Receipt

**Comment by roquegv** [comment]
From @wojosc 

> many e-mail run into our erp with attached invoices. At the moment all e-mails that go to e.g. [post@phamos.eu](mailto:post@phamos.eu), [support@phamos.eu](mailto:support@phamos.eu) or [mail@phamos.eu](mailto:mail@phamos.eu) go into the system and create a new Issue or are attached to an existing one (this is a details that we will not have to concider in the first step).
> 
> Now, as we will wan't to have all incoming vouchers as accounting receipt my life would be a lot easier, if I had a "Convert to Accounting Receipt" button on the Issue doctype.
> 
> This would:
> 
>     create a instance of Accounting Receipttransfert the linked Communication to Accounting ReceiptExtract and attach all Files (attachments) from Communication to Accounting Receiptpost a url of the new Accounting Receipt as a comment into the IssueClose the Issue

**Comment by roquegv** [comment]
Important points from the meeting:
- In Accounting Receipt include the Timesheet table
- Have a "Fetching Timesheets" button inside the Accounting Receipt form
- Use the Activity Cost doctype for set the Hourly Rate
- Use a generic "Service" Item
- Create Phamos Setting (single doctype): with "Service item" field in it (for now) 
- Discuss with Wolfram if we need to create Accounting Receipt from Timesheet or Timesheet Record (or both)
    - Update the Timesheet Record when the Timesheet is submitted
- Have a submit process for the Accounting Receipt doctype (update the billing amount in Timesheet, for example)
- When creating Purchase Invoice, consider the Time Sheet table in that doctype
