### ISSUE TITLE
Merge project_addon app

### ISSUE THREAD

**Issue by beingeek** [phamos-eu/phamos#4]
## The goal
To merge to project project_addon in phamos.eu app for phamos specific customization. 

## TODOs
- [ ] Migrate all doctype and features from project_addon.
- [ ] QA for any possible bugs.
- [ ] Test phamos app for any possible bugs related to migration.
- [ ] Install on server
- [ ] Archive project_addon.
