### ISSUE TITLE
Team page and Team members profile page

### ISSUE THREAD

**Issue by beingeek** [phamos-eu/phamos#9]
## The goal
The goal is to make a Web Page for Team also web page for each team member profile.

## Context
- There will be Web Page (URL: https://phamos.eu/about), in this web page all team members photos will be showcase with clickable link route to Web Page for each user profile (URL: https://phamos.eu/profile/user-id-or-name). On User profile page there will be some information rendered about user illustrated as below image.

Profile Image:
![image](https://github.com/phamos-eu/phamos/assets/25414115/52d4f3fa-c036-4d53-b2c2-74104107ee60)

Team Section on About page:
![image](https://github.com/phamos-eu/phamos/assets/25414115/162d23f7-f7e8-4d9d-97ab-31cb35f0907a)

## TODOs
- [x] Preparing Data source for rendering about page, a new child table in 'About Us Settings' Doctype can be added which will carry data of profile links web page and user images. 
- [x] Preparing Data source Doctype for user profile web page, Employee Doctype can be used to store information about user profile (Bio/Personal information, Project and module links, Personal Testimonial and Social media links of employee)
- [x] Choosing URL for team page (URL: https://phamos.eu/about) or (URL: https://phamos.eu/team)
- [x] Working on design of Web Page 
- [x] Demonstrating a dummy Web Page 
- [ ] Making Web Pages live
